blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.com/invite/v3W4YsuBCw
    about: Ask questions and discuss with other devs in \#zkapps-developers channel on Mina's Discord.
