#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm run test

          # Test generic template
          cd templates/project-ts
          npm ci || true
          npm run test
          rm -rf node_modules
          cd ../..

          # Ensure example apps are working
          npm link

          zk example sudoku
          cd sudoku
          npm run test
          npm run build
          npm run start
          cd ..
          rm -rf sudoku

          zk example tictactoe
          cd tictactoe
          npm run test
          npm run build
          npm run start
          cd ..
          rm -rf tictactoe
        env:
          CI: true
      - name: Publish to NPM if version has changed
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
