name: E2E Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Dependencies, build and link the CLI app
        run: |
          npm ci
          npm run build --if-present
          npm link
      - name: Install Playwright Dependencies
        run: npm run e2e:install
      - name: Execute E2E Tests on ${{ matrix.os }}
        run: npm run e2e:test
        env:
          CI: true
      - name: Upload E2E Test Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-tests-report-node${{ matrix.node }}-${{ matrix.os }}
          path: reports/html-report/
          retention-days: 30
