#
# https://github.com/stackblitz-labs/pkg.pr.new
#

name: Continuous releases on pkg-pr-new
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  pkg-pr-new-o1js:
    strategy:
      matrix:
        node: [20]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.JS ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Build the application
        run: |
          npm ci
          npm run build --if-present
      - name: Publish on pkg-pr-new
        run: npx pkg-pr-new publish # Enable `--compact` once published to NPM with `repository` in package.json
