#
# This workflow will publish the package to NPM when the following conditions are met:
#  - The workflow run was triggered by the successful completion of the 'Smoke E2E tests' workflow
#  - The target branch is 'origin/main'
#

name: Publish to NPM
on:
  workflow_run:
    workflows: ['Smoke E2E tests']
    types: [completed]
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: NPM ci & build
        run: |
          npm ci
          npm run build --if-present
      - name: Publish to NPM if version has changed
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
