#
# This workflow will run common unit tests, and then run the Sudoku and TicTacToe examples unit tests if the common unit tests pass.
#

name: Unit tests
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  common:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm run coverage
          cd templates/project-ts
          npm install || true
          npm run test
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: zkapp-cli
          verbose: true
          handle_no_reports_found: true
          fail_ci_if_error: false
  sudoku-example:
    runs-on: ubuntu-latest
    needs: [common]
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "unit-tests@o1labs.org"
          git config --global user.name "Unit Tests"
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm link
          zk example sudoku
          cd sudoku
          npm run test
          npm run build
          npm run start
        env:
          CI: true
  tictactoe-example:
    runs-on: ubuntu-latest
    needs: [common]
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "unit-tests@o1labs.org"
          git config --global user.name "Unit Tests"
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm link
          zk example tictactoe
          cd tictactoe
          npm run test
          npm run build
          npm run start
        env:
          CI: true
